name: foodstack
description: Flutter app by Team APPetite.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  fluttertoast: ^8.0.7
  provider: ^5.0.0
  geolocator: ^7.0.3
  http: ^0.13.3
  google_maps_flutter: ^2.0.6
  geocoder: ^0.2.1
  cloud_firestore: ^2.2.0
  uuid: ^3.0.4
  flutter_number_picker: ^1.0.1
  numberpicker: ^2.1.1
  geoflutterfire: ^3.0.0-nullsafety.4
  firebase_messaging: ^10.0.2
  shared_preferences: ^2.0.6
  flutter_braintree: ^1.2.1
  flutter_local_notifications: ^6.0.0
  flutter_native_timezone: ^2.0.0
  fake_cloud_firestore: ^1.1.2
  firebase_auth_mocks: ^0.7.1
  google_sign_in_mocks: ^0.2.1
  google_sign_in: ^5.0.2
  flutter_signin_button: ^1.1.0
  flutter_rating_bar: ^3.2.0
  chips_choice: ^2.0.1
  firebase_analytics: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^5.0.10

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
  - family: Montserrat
    fonts:
        - asset: fonts/Montserrat-Regular.ttf
