name: integration tests
on: [push]
jobs:
  android-integration-test:
    name: run integration test on Android emulator
    runs-on: macos-latest
    strategy:
      matrix:
        device:
          - "pixel_xl"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.2.0'
      - name: run tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2.15.0
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          api-level: 29
          profile: ${{ matrix.device }}
          script: |
            /Users/runner/Library/Android/sdk/tools/bin/avdmanager list
            sleep 20
            ./scripts/setenv.sh
            flutter doctor -v
            cd ./photochatapp && export ANDROID_DEBUG=true && flutter pub get && flutter drive --target=test_driver/app.dart --no-sound-null-safety
