name:  integration tests
on: [push,pull_request]

jobs:

  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.2.0'
      - run: flutter pub get

  drive_android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [27]
        target: [default]
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.2.0'
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: |
            cd ./FoodStack
            flutter pub get
            flutter drive --target=test_driver/app.dart
